### ISSUE TITLE
No module named 'openpifpaf_tracker'

### ISSUE THREAD

**Issue by MichaelWU0726** [vita-epfl/openpifpaf-torchhub#1]
I have installed openpifpaf v0.12.5. When i load checkpoint v0.12.2 release 'tshufflenetv2k30-210222-112623-posetrack2018-cocokpst-o10-123ec670.pkl' in torch1.6.0, it showed the following:
`Traceback (most recent call last):
  File "~/programs/pycharm/projects/pifpaf/16to13.py", line 7, in <module>
      model = torch.load(ckpt)
  File "~/programs/anaconda3/envs/pt160/lib/python3.8/site-packages/torch/serialization.py", line 595, in load
      return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "~/programs/anaconda3/envs/pt160/lib/python3.8/site-packages/torch/serialization.py", line 764, in _legacy_load
      magic_number = pickle_module.load(f, **pickle_load_args)
ModuleNotFoundError: No module named 'openpifpaf_tracker'`

what's more, in torch1.3, it showed that:
`the checkpoint is a zip archive(did you mean to use torch.jit.load()?)`
But i switch to use `torch.jit.load()` and there was one more error:
`RuntimeError: version_number <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /tmp/pip-req-build-4baxydiv/caffe2/serialize/inline_container.cc:131, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 1. Your PyTorch installation may be too old. (init at /tmp/pip-req-build-4baxydiv/caffe2/serialize/inline_container.cc:131)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6d (0x7fe2663d3e7d in ~/programs/anaconda3/envs/falldetection_openpifpaf/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x246d (0x7fe2689cc38d in ~/programs/anaconda3/envs/falldetection_openpifpaf/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x69 (0x7fe2689cd849 in ~/programs/anaconda3/envs/falldetection_openpifpaf/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: torch::jit::import_ir_module(std::shared_ptr<torch::jit::script::CompilationUnit>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0x4d (0x7fe269ca2a3d in ~/programs/anaconda3/envs/falldetection_openpifpaf/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #4: <unknown function> + 0x5c83fa (0x7fe287e993fa in ~/programs/anaconda3/envs/falldetection_openpifpaf/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x201bab (0x7fe287ad2bab in ~/programs/anaconda3/envs/falldetection_openpifpaf/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: _PyMethodDef_RawFastCallKeywords + 0x274 (0x555847308914 in ~/programs/anaconda3/envs/falldetection_openpifpaf/bin/python)
frame #7: _PyCFunction_FastCallKeywords + 0x21 (0x555847308a31 in ~/programs/anaconda3/envs/falldetection_openpifpaf/bin/python)
frame #8: _PyEval_EvalFrameDefault + 0x4e1d (0x555847374ebd in ~/programs/anaconda3/envs/falldetection_openpifpaf/bin/python)
frame #9: _PyEval_EvalCodeWithName + 0x2f9 (0x5558472b7829 in ~/programs/anaconda3/envs/falldetection_openpifpaf/bin/python)
frame #10: _PyFunction_FastCallKeywords + 0x325 (0x5558473080a5 in ~/programs/anaconda3/envs/falldetection_openpifpaf/bin/python)
frame #11: _PyEval_EvalFrameDefault + 0x4a89 (0x555847374b29 in ~/programs/anaconda3/envs/falldetection_openpifpaf/bin/python)
frame #12: _PyEval_EvalCodeWithName + 0x2f9 (0x5558472b7829 in ~/programs/anaconda3/envs/falldetection_openpifpaf/bin/python)
frame #13: _PyFunction_FastCallKeywords + 0x387 (0x555847308107 in ~/programs/anaconda3/envs/falldetection_openpifpaf/bin/python)
frame #14: _PyEval_EvalFrameDefault + 0x14e5 (0x555847371585 in ~/programs/anaconda3/envs/falldetection_openpifpaf/bin/python)
frame #15: _PyFunction_FastCallKeywords + 0xfb (0x555847307e7b in ~/programs/anaconda3/envs/falldetection_openpifpaf/bin/python)`

**Comment by svenkreiss** [comment]
OpenPifPaf v0.12.5 requires pytorch 1.7.1 or later:
https://github.com/vita-epfl/openpifpaf/blob/a1ad952b14e3a712bcef16832aea8d628927b15b/setup.py#L58
That is not in our control. PyTorch changed their serialization format.

Please use the main repository for issues. I'll try to deactivate them here.
